name: Enhance Github Issue

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

jobs:
  enhance-github-issue:
    permissions:
      issues: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Enhance GitHub Issue
        uses: malcmiller/tpm-agent@v1
        with:
          check_all: "True"
          github_event_name: ${{ github.event_name }}
          github_issue_id: ${{ github.event.issue.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_issue_comment_id: ${{ github.event.comment.id }}
          azure_openai_target_uri: ${{ secrets.AZURE_OPENAI_TARGET_URI }}
          azure_openai_api_key: ${{ secrets.AZURE_OPENAI_API_KEY }}
          repository: ${{ github.repository }}

