name: Enhance Github Issue

on:
  issues:
    types:
      - opened

jobs:
  enhance-github-issue:
    permissions:
      issues: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Enhance GitHub Issue
        uses: malcmiller/issue-enhancer-agent@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          azure_openai_endpoint: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          azure_openai_deployment: ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
          issue_id: ${{ github.event.issue.number }}
          issue_title: ${{ github.event.issue.title }}
          issue_body: ${{ github.event.issue.body }}
